import {
  ApplicationConfig,
  inject,
  provideAppInitializer,
  provideBrowserGlobalErrorListeners,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { appRoutes } from './app.routes';
import { authInterceptor } from './core/auth/interceptors/auth.interceptor';
import { AuthService } from './core/auth/services/auth.service';
import {
  LUCIDE_ICONS,
  LucideIconProvider,
  AlertCircle,
  AlertTriangle,
  AlignJustify,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Calendar,
  CalendarRange,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown, ChevronsDown, ChevronsUp,
  ChessRook,
  CircleAlert,
  CirclePile,
  Clock,
  Construction,
  Copy,
  DraftingCompass,
  ExternalLink,
  Eye,
  Flower,
  GitCommitHorizontal,
  Grid3X3,
  Home,
  Keyboard,
  LayoutGrid,
  List,
  Lock,
  Magnet,
  Mail,
  Maximize2,
  Menu,
  Minus,
  MoreHorizontal,
  MousePointer2,
  MousePointerClick,
  PanelRightClose,
  PanelRightOpen,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Tag,
  Trash2,
  UserCog,
  UserX,
  Users,
  X, EyeOff, FolderOpen, Info, GitBranch, CircleQuestionMark, PlusCircle, UserCheck, Edit, Import, ArrowUpDown, ArrowDownUp,
  GripVertical, PanelLeft, PanelLeftClose, Monitor, PlusSquare, Square, MoveRight, Moon, Sun,
  BookOpen, RotateCcw, RotateCw, History, UserPlus, Baby, UsersRound, StickyNote, UserMinus,
  ClipboardCheck, Undo2, Redo2, Ghost
} from 'lucide-angular';

const icons = {
  AlertCircle, AlertTriangle, AlignJustify, ArrowDown, ArrowLeft, ArrowUp,
  Calendar, CalendarRange, Check,
  ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsUpDown, ChevronsDown, ChevronsUp,
  ChessRook, CircleAlert, CirclePile, Clock, Construction, Copy, DraftingCompass, ExternalLink, Eye,
  Flower, GitCommitHorizontal,
  Grid3X3, Home, Keyboard, LayoutGrid, List, Lock, Magnet, Mail, Maximize2, Menu, Minus,
  MoreHorizontal, MousePointer2, MousePointerClick,
  PanelRightClose, PanelRightOpen, Pencil, Plus, RefreshCw, Search, Settings, Shapes, Shield,
  ShieldCheck,
  Sparkles, Star, Tag, Trash2, UserCog, UserX, Users, X, EyeOff, FolderOpen, Info, GitBranch,
  CircleQuestionMark, PlusCircle, UserCheck, Edit, Import, ArrowUpDown, ArrowDownUp,
  GripVertical, PanelLeft, PanelLeftClose, Monitor, PlusSquare, Square, MoveRight, Moon, Sun,
  BookOpen, RotateCcw, RotateCw, History, UserPlus, Baby, UsersRound, StickyNote, UserMinus,
  ClipboardCheck, Undo2, Redo2, Ghost
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(appRoutes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAppInitializer(() => inject(AuthService).init()),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useFactory: () => new LucideIconProvider(icons),
    },
  ],
};
