export enum EventReferenceKind {
  SPECIFIC = 'SPECIFIC',
  NEXT_ACTUACIO = 'NEXT_ACTUACIO',
  NEXT_ASSAIG = 'NEXT_ASSAIG',
  NEXT_ACTUACIO_OR_ASSAIG = 'NEXT_ACTUACIO_OR_ASSAIG',
  TRIGGERING_EVENT = 'TRIGGERING_EVENT',
}
