export enum NodeShape {
  ELLIPSE = 'ELLIPSE',
  RECTANGLE = 'RECTANGLE',
  ARROW = 'ARROW',
  ARROW_LEFT = 'ARROW_LEFT',
  ARROW_UP = 'ARROW_UP',
  ARROW_DOWN = 'ARROW_DOWN',
  DOUBLE_ARROW = 'DOUBLE_ARROW',
  TRIANGLE = 'TRIANGLE',
  STAR = 'STAR',
  CIRCLE = 'CIRCLE',
}
